name: Build
on: [push]
jobs:
  build-project:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Install Doxygen & Graphviz
        run: sudo apt-get install doxygen graphviz -y
        shell: bash

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Build the project
        run: cmake --build build

      - name: Build the  documentation
        run: cmake --build build --target doxygen

      # - name: Test the project
      #   run: ctest --test-dir build